export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const AUTHENTICATION_HAS_ERRORED = 'AUTHENTICATION_HAS_ERRORED';