export const AIRPORT_HAS_ERRORED = 'AIRPORT_HAS_ERRORED';
export const AIRPORT_FETCH_DATA_SUCCESS = 'AIRPORT_FETCH_DATA_SUCCESS';
export const TICKETS_IS_LOADING = 'TICKETS_IS_LOADING';
export const TICKETS_HAS_ERRORED = 'TICKETS_HAS_ERRORED';
export const TICKETS_FETCH_DATA_SUCCESS = 'TICKETS_FETCH_DATA_SUCCESS';
export const BESTDEALS_IS_LOADING = 'BESTDEALS_IS_LOADING';
export const BESTDEALS_HAS_ERRORED = 'BESTDEALS_HAS_ERRORED';
export const BESTDEALS_FETCH_DATA_SUCCES = 'BESTDEALS_FETCH_DATA_SUCCES';