export const AIRPORT_HAS_ERRORED = 'AIRPORT_HAS_ERRORED';
export const AIRPORT_FETCH_DATA_SUCCESS = 'AIRPORT_FETCH_DATA_SUCCESS';
export const TICKETS_IS_LOADING = 'TICKETS_IS_LOADING';
export const TICKETS_HAS_ERRORED = 'TICKETS_HAS_ERRORED';
export const TICKETS_FETCH_DATA_SUCCESS = 'TICKETS_FETCH_DATA_SUCCESS';